# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_desc',
            name='desc',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='software_desc',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='software_desc',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='software_desc',
            name='totaldownloads',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='software_desc',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
