# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170712_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software_desc',
            old_name='totaldownloads',
            new_name='total_downloads',
        ),
    ]
