# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170712_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_desc',
            name='desc',
            field=models.TextField(),
        ),
    ]
