# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170712_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win_32',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
