# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170713_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win_32',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
