# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170713_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win_32',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.software_desc'),
        ),
    ]
