# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170713_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software_desc',
            name='id',
        ),
        migrations.AlterField(
            model_name='software_desc',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
